project_id = "mdmhvlngucgbppwkzwcd"

[functions.send-periodic-hr-emails]
verify_jwt = false

[functions.notify-project-submission]
verify_jwt = true

[functions.notify-training-session]
verify_jwt = true

[functions.notify-training-session-crm]
verify_jwt = true

[functions.extract-modules-from-content]
verify_jwt = true

[functions.update-user-email]
verify_jwt = true

[functions.extract-course-and-modules]
verify_jwt = false
